steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/appraisers-task-queue:$SHORT_SHA',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/appraisers-task-queue:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'appraisers-task-queue'
    - '--image'
    - 'gcr.io/$PROJECT_ID/appraisers-task-queue:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets'
    - 'SENDGRID_API_KEY=SENDGRID_API_KEY:latest,SENDGRID_EMAIL=SENDGRID_EMAIL:latest,SEND_GRID_TEMPLATE_NOTIFY_APPRAISAL_COMPLETED=SEND_GRID_TEMPLATE_NOTIFY_APPRAISAL_COMPLETED:latest,PENDING_APPRAISALS_SPREADSHEET_ID=PENDING_APPRAISALS_SPREADSHEET_ID:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,WORDPRESS_REST_URL=WORDPRESS_REST_URL:latest,WORDPRESS_APPLICATION_PASSWORD=WORDPRESS_APPLICATION_PASSWORD:latest,GOOGLE_CLOUD_PROJECT=GOOGLE_CLOUD_PROJECT:latest,PUBSUB_TOPIC_CRM_MESSAGES=PUBSUB_TOPIC_CRM_MESSAGES:latest'
    - '--set-env-vars'
    - 'PUBSUB_SUBSCRIPTION_NAME=CRM-tasks'
    - '--memory'
    - '2Gi'

images:
  - 'gcr.io/$PROJECT_ID/appraisers-task-queue:$SHORT_SHA'